### PR TITLE
replace layer name cquery with lsp-c-c++

### PR DESCRIPTION
**Pull request by iromise**

### CODE REVIEW

**Comment by iromise** [comment]
And, by the way, I'm a liitle confused when I replaced all cquery with ccls, it gives the following info
```
Error (use-package): ccls/:config: Key sequence r r starts with non-prefix key r
```
I couldn't find any `r r` in the config file.
and when I comment rr in lsp config, it is ok, but it gives the following 
```
Warning (lsp-mode): Unknown method: $ccls/setSkippedRanges
```

**Review by cormacc — COMMENTED** [review]
Thanks iromise. I've made the suggested changes via an amended commit rather than accepting this, as want to keep the PR against upstream spacemacs as a single commit.

**Comment by cormacc** [comment]
Re. ccls - haven't had time to play with that yet. Just got back to a bit of C last week, and fairly busy

**Comment by iromise** [comment]
Thanks, I wish i could still leave this pr here so that someday to solve the ccls related problem.

**Comment by myrgy** [comment]
IT might be great to support both tools, currrently they are moving in same direction, so we'll have ability to compare easily.

**Comment by cormacc** [comment]
@myrgy Supporting both tools is the intention, when next I get a bit of idle time. cquery by default, with the option to use ccls via a config variable.

**Comment by iromise** [comment]
sorry for say here, I find when use ccls enabled with sem rainbow, it gives the error

Error (use-package): ccls/:config: Invalid function: ccls-use-default-rainbow-sem-highlight

**Comment by cormacc** [comment]
@iromise Good catch - hadn't enabled sem rainbow in a while. See the same issue with both cquery and ccls backends. The macro definitions exist in both cases, they're just not in scope when called and they used to be -- don't know whether it's something I've done or an upstream change. I'll be working on integrating this work with the c-c++ layer next week sometime and will take a proper look then.

**Comment by iromise** [comment]
Thanks! And looking forward to your big work of this integration!

**Comment by myrgy** [comment]
since   ccls/cquery-use-default-rainbow-sem-highlight is a macro it's still possible to call it using name.
switch or if might be a solution in that case.

**Pull request closed without merging**
